const AUDIO_DATA = [

    {
        genre : 'Romance',
        id : 0,
        books : [
            {
                id : 0,
                title : 'Count of Monte Cristo',
                author : 'Alexandre Dumas',
                description : 'The Count of Monte Cristo (French: Le Comte de Monte-Cristo) is an adventure novel by Alexandre Dumas, père. It is often considered, along with The Three Musketeers, as Dumass most popular work. The writing of the work was completed in 1844. Like many of his novels, it is expanded from the plot outlines suggested by his collaborating ghostwriter Auguste Maquet.The story takes place in France, Italy, islands in the Mediterranean and the Levant during the historical events of 1815–1838 (from just before the Hundred Days through the reign of Louis-Philippe of France). The historical setting is a fundamental element of the book. It is primarily concerned with themes of justice, vengeance, mercy, and forgiveness, and is told in the style of an adventure story',
                img_url : 'https://www.rif.org/sites/default/files/Book_Covers/CountMonte.jpg',
                chapters : [
                    { id : 0, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_001_dumas_64kb.mp3' }, 
                    { id : 1, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_002_dumas_64kb.mp3' }, 
                    { id : 2, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_003_dumas_64kb.mp3' }, 
                    { id : 3, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_004_dumas_64kb.mp3' }, 
                    { id : 4, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_005_dumas_64kb.mp3' }, 
                    { id : 5, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_006_dumas_64kb.mp3' }, 
                    { id : 6, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_007_dumas_64kb.mp3' }, 
                    { id : 7, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_008_dumas_64kb.mp3' }, 
                    { id : 8, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_009_dumas_64kb.mp3' }, 
                    { id : 9, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_010_dumas_64kb.mp3' }, 
                    { id : 10, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_011_dumas_64kb.mp3' }, 
                    { id : 11, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_012_dumas_64kb.mp3' }, 
                    { id : 12, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_013_dumas_64kb.mp3' }, 
                    { id : 13, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_014_dumas_64kb.mp3' }, 
                    { id : 14, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_015_dumas_64kb.mp3' }, 
                    { id : 15, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_016_dumas_64kb.mp3' }, 
                    { id : 16, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_017_dumas_64kb.mp3' }, 
                    { id : 17, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_018_dumas_64kb.mp3' }, 
                    { id : 18, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_019_dumas_64kb.mp3' }, 
                    { id : 19, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_020_dumas_64kb.mp3' }, 
                    { id : 20, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_021_dumas_64kb.mp3' }, 
                    { id : 21, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_022_dumas_64kb.mp3' }, 
                    { id : 22, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_023_dumas_64kb.mp3' }, 
                    { id : 23, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_024_dumas_64kb.mp3' }, 
                    { id : 24, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_025_dumas_64kb.mp3' }, 
                    { id : 25, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_026_dumas_64kb.mp3' }, 
                    { id : 26, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_027_dumas_64kb.mp3' }, 
                    { id : 27, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_028_dumas_64kb.mp3' }, 
                    { id : 28, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_029_dumas_64kb.mp3' }, 
                    { id : 29, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_030_dumas_64kb.mp3' }, 
                    { id : 30, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_031_dumas_64kb.mp3' }, 
                    { id : 31, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_032_dumas_64kb.mp3' }, 
                    { id : 32, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_033_dumas_64kb.mp3' }, 
                    { id : 33, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_034_dumas_64kb.mp3' }, 
                    { id : 34, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_035_dumas_64kb.mp3' }, 
                    { id : 35, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_036_dumas_64kb.mp3' }, 
                    { id : 36, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_037_dumas_64kb.mp3' }, 
                    { id : 37, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_038_dumas_64kb.mp3' }, 
                    { id : 38, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_039_dumas_64kb.mp3' }, 
                    { id : 39, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_040_dumas_64kb.mp3' }, 
                    { id : 40, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_041_dumas_64kb.mp3' }, 
                    { id : 41, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_042_dumas_64kb.mp3' }, 
                    { id : 42, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_043_dumas_64kb.mp3' }, 
                    { id : 43, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_044_dumas_64kb.mp3' }, 
                    { id : 44, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_045_dumas_64kb.mp3' }, 
                    { id : 45, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_046_dumas_64kb.mp3' }, 
                    { id : 46, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_047_dumas_64kb.mp3' }, 
                    { id : 47, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_048_dumas_64kb.mp3' }, 
                    { id : 48, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_049_dumas_64kb.mp3' }, 
                    { id : 49, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_050_dumas_64kb.mp3' }, 
                    { id : 50, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_051_dumas_64kb.mp3' }, 
                    { id : 51, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_052_dumas_64kb.mp3' }, 
                    { id : 52, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_053_dumas_64kb.mp3' }, 
                    { id : 53, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_054_dumas_64kb.mp3' }, 
                    { id : 54, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_055_dumas_64kb.mp3' }, 
                    { id : 55, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_056_dumas_64kb.mp3' }, 
                    { id : 56, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_057_dumas_64kb.mp3' }, 
                    { id : 57, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_058_dumas_64kb.mp3' }, 
                    { id : 58, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_059_dumas_64kb.mp3' }, 
                    { id : 59, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_060_dumas_64kb.mp3' }, 
                    { id : 60, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_061_dumas_64kb.mp3' }, 
                    { id : 61, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_062_dumas_64kb.mp3' }, 
                    { id : 62, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_063_dumas_64kb.mp3' }, 
                    { id : 63, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_064_dumas_64kb.mp3' }, 
                    { id : 64, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_065_dumas_64kb.mp3' }, 
                    { id : 65, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_066_dumas_64kb.mp3' }, 
                    { id : 66, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_067_dumas_64kb.mp3' }, 
                    { id : 67, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_068_dumas_64kb.mp3' }, 
                    { id : 68, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_069_dumas_64kb.mp3' }, 
                    { id : 69, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_070_dumas_64kb.mp3' }, 
                    { id : 70, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_071_dumas_64kb.mp3' }, 
                    { id : 71, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_072_dumas_64kb.mp3' }, 
                    { id : 72, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_073_dumas_64kb.mp3' }, 
                    { id : 73, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_074_dumas_64kb.mp3' }, 
                    { id : 74, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_075_dumas_64kb.mp3' }, 
                    { id : 75, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_076_dumas_64kb.mp3' }, 
                    { id : 76, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_077_dumas_64kb.mp3' }, 
                    { id : 77, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_078_dumas_64kb.mp3' }, 
                    { id : 78, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_079_dumas_64kb.mp3' }, 
                    { id : 79, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_080_dumas_64kb.mp3' }, 
                    { id : 80, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_081_dumas_64kb.mp3' }, 
                    { id : 81, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_082_dumas_64kb.mp3' }, 
                    { id : 82, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_083_dumas_64kb.mp3' }, 
                    { id : 83, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_084_dumas_64kb.mp3' }, 
                    { id : 84, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_085_dumas_64kb.mp3' }, 
                    { id : 85, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_086_dumas_64kb.mp3' }, 
                    { id : 86, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_087_dumas_64kb.mp3' }, 
                    { id : 87, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_088_dumas_64kb.mp3' }, 
                    { id : 88, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_089_dumas_64kb.mp3' }, 
                    { id : 89, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_090_dumas_64kb.mp3' }, 
                    { id : 90, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_091_dumas_64kb.mp3' }, 
                    { id : 91, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_092_dumas_64kb.mp3' }, 
                    { id : 92, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_093_dumas_64kb.mp3' }, 
                    { id : 93, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_094_dumas_64kb.mp3' }, 
                    { id : 94, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_095_dumas_64kb.mp3' }, 
                    { id : 95, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_096_dumas_64kb.mp3' }, 
                    { id : 96, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_097_dumas_64kb.mp3' }, 
                    { id : 97, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_098_dumas_64kb.mp3' }, 
                    { id : 98, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_099_dumas_64kb.mp3' }, 
                    { id : 99, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_100_dumas_64kb.mp3' }, 
                    { id : 100, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_101_dumas_64kb.mp3' }, 
                    { id : 101, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_102_dumas_64kb.mp3' }, 
                    { id : 102, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_103_dumas_64kb.mp3' }, 
                    { id : 103, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_104_dumas_64kb.mp3' }, 
                    { id : 104, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_105_dumas_64kb.mp3' }, 
                    { id : 105, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_106_dumas_64kb.mp3' }, 
                    { id : 106, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_107_dumas_64kb.mp3' }, 
                    { id : 107, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_108_dumas_64kb.mp3' }, 
                    { id : 108, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_109_dumas_64kb.mp3' }, 
                    { id : 109, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_110_dumas_64kb.mp3' }, 
                    { id : 110, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_111_dumas_64kb.mp3' }, 
                    { id : 111, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_112_dumas_64kb.mp3' }, 
                    { id : 112, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_113_dumas_64kb.mp3' }, 
                    { id : 113, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_114_dumas_64kb.mp3' }, 
                    { id : 114, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_115_dumas_64kb.mp3' }, 
                    { id : 115, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_116_dumas_64kb.mp3' }, 
                    { id : 116, url :  ' http://www.archive.org/download/count_monte_cristo_0711_librivox/count_of_monte_cristo_117_dumas_64kb.mp3' }, 
                   
                ]
            
            },
            {
                id : 1,
                title : 'This Side of Paradise ',
                author : 'Scott Fitzgerald',
                description : 'This Side of Paradise is the debut novel of F. Scott Fitzgerald. Published in 1920, and taking its title from a line of the Rupert Brooke poem Tiare Tahiti, the book examines the lives and morality of post-World War I youth. Its protagonist, Amory Blaine, is a wealthy and attractive Princeton University student who dabbles in literature and has a series of romances that eventually lead to his disillusionment. In his later novels, Fitzgerald would further develop the books theme of love warped by greed and status-seeking. ',
                img_url : 'https://upload.wikimedia.org/wikipedia/commons/0/01/This_Side_of_Paradise_dust_jacket.jpg',
                chapters : [
                    { id : 0, url :  ' http://www.archive.org/download/this_side_paradise_librivox/thissideofparadise_01_fitzgerald_64kb.mp3' }, 
         { id : 1, url :  ' http://www.archive.org/download/this_side_paradise_librivox/thissideofparadise_02_fitzgerald_64kb.mp3' }, 
         { id : 2, url :  ' http://www.archive.org/download/this_side_paradise_librivox/thissideofparadise_03_fitzgerald_64kb.mp3' }, 
         { id : 3, url :  ' http://www.archive.org/download/this_side_paradise_librivox/thissideofparadise_04_fitzgerald_64kb.mp3' }, 
         { id : 4, url :  ' http://www.archive.org/download/this_side_paradise_librivox/thissideofparadise_05_fitzgerald_64kb.mp3' }, 
         { id : 5, url :  ' http://www.archive.org/download/this_side_paradise_librivox/thissideofparadise_06_fitzgerald_64kb.mp3' }, 
         { id : 6, url :  ' http://www.archive.org/download/this_side_paradise_librivox/thissideofparadise_07_fitzgerald_64kb.mp3' }, 
         { id : 7, url :  ' http://www.archive.org/download/this_side_paradise_librivox/thissideofparadise_08_fitzgerald_64kb.mp3' }, 
         { id : 8, url :  ' http://www.archive.org/download/this_side_paradise_librivox/thissideofparadise_09_fitzgerald_64kb.mp3' }, 
         { id : 9, url :  ' http://www.archive.org/download/this_side_paradise_librivox/thissideofparadise_10_fitzgerald_64kb.mp3' }, 
         { id : 10, url :  ' http://www.archive.org/download/this_side_paradise_librivox/thissideofparadise_11_fitzgerald_64kb.mp3' }, 
         { id : 11, url :  ' http://www.archive.org/download/this_side_paradise_librivox/thissideofparadise_12_fitzgerald_64kb.mp3' }, 
         { id : 12, url :  ' http://www.archive.org/download/this_side_paradise_librivox/thissideofparadise_13_fitzgerald_64kb.mp3' }, 
         { id : 13, url :  ' http://www.archive.org/download/this_side_paradise_librivox/thissideofparadise_14_fitzgerald_64kb.mp3' }, 
         { id : 14, url :  ' http://www.archive.org/download/this_side_paradise_librivox/thissideofparadise_15_fitzgerald_64kb.mp3' }, 
         { id : 15, url :  ' http://www.archive.org/download/this_side_paradise_librivox/thissideofparadise_16_fitzgerald_64kb.mp3' }, 
         { id : 16, url :  ' http://www.archive.org/download/this_side_paradise_librivox/thissideofparadise_17_fitzgerald_64kb.mp3' }, 
         { id : 17, url :  ' http://www.archive.org/download/this_side_paradise_librivox/thissideofparadise_18_fitzgerald_64kb.mp3' }, 
         { id : 18, url :  ' http://www.archive.org/download/this_side_paradise_librivox/thissideofparadise_19_fitzgerald_64kb.mp3' }, 
         { id : 19, url :  ' http://www.archive.org/download/this_side_paradise_librivox/thissideofparadise_20_fitzgerald_64kb.mp3' }, 
         { id : 20, url :  ' http://www.archive.org/download/this_side_paradise_librivox/thissideofparadise_21_fitzgerald_64kb.mp3' }, 
         { id : 21, url :  ' http://www.archive.org/download/this_side_paradise_librivox/thissideofparadise_22_fitzgerald_64kb.mp3' }, 
        
                ]
            },
            {
                id : 2,
                title : 'Twenty Years After',
                author : 'Alexandre Dumas',
                description : 'Lets continue the DArtagnan Romances that weve already started with The Three Musketeers.',
                img_url : 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1165607713l/7184.jpg',
                chapters : [
                    { id : 0, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_01_dumas_64kb.mp3' }, 
         { id : 1, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_02_dumas_64kb.mp3' }, 
         { id : 2, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_03_dumas_64kb.mp3' }, 
         { id : 3, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_04_dumas_64kb.mp3' }, 
         { id : 4, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_05_dumas_64kb.mp3' }, 
         { id : 5, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_06_dumas_64kb.mp3' }, 
         { id : 6, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_07_dumas_64kb.mp3' }, 
         { id : 7, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_08_dumas_64kb.mp3' }, 
         { id : 8, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_09_dumas_64kb.mp3' }, 
         { id : 9, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_10_dumas_64kb.mp3' }, 
         { id : 10, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_11_dumas_64kb.mp3' }, 
         { id : 11, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_12_dumas_64kb.mp3' }, 
         { id : 12, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_13_dumas_64kb.mp3' }, 
         { id : 13, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_14_dumas_64kb.mp3' }, 
         { id : 14, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_15_dumas_64kb.mp3' }, 
         { id : 15, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_16_dumas_64kb.mp3' }, 
         { id : 16, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_17_dumas_64kb.mp3' }, 
         { id : 17, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_18_dumas_64kb.mp3' }, 
         { id : 18, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_19_dumas_64kb.mp3' }, 
         { id : 19, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_20_dumas_64kb.mp3' }, 
         { id : 20, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_21_dumas_64kb.mp3' }, 
         { id : 21, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_22_dumas_64kb.mp3' }, 
         { id : 22, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_23_dumas_64kb.mp3' }, 
         { id : 23, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_24_dumas_64kb.mp3' }, 
         { id : 24, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_25_dumas_64kb.mp3' }, 
         { id : 25, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_26_dumas_64kb.mp3' }, 
         { id : 26, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_27_dumas_64kb.mp3' }, 
         { id : 27, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_28_dumas_64kb.mp3' }, 
         { id : 28, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_29_dumas_64kb.mp3' }, 
         { id : 29, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_30_dumas_64kb.mp3' }, 
         { id : 30, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_31_dumas_64kb.mp3' }, 
         { id : 31, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_32_dumas_64kb.mp3' }, 
         { id : 32, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_33_dumas_64kb.mp3' }, 
         { id : 33, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_34_dumas_64kb.mp3' }, 
         { id : 34, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_35_dumas_64kb.mp3' }, 
         { id : 35, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_36_dumas_64kb.mp3' }, 
         { id : 36, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_37_dumas_64kb.mp3' }, 
         { id : 37, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_38_dumas_64kb.mp3' }, 
         { id : 38, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_39_dumas_64kb.mp3' }, 
         { id : 39, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_40_dumas_64kb.mp3' }, 
         { id : 40, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_41_dumas_64kb.mp3' }, 
         { id : 41, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_42_dumas_64kb.mp3' }, 
         { id : 42, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_43_dumas_64kb.mp3' }, 
         { id : 43, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_44_dumas_64kb.mp3' }, 
         { id : 44, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_45_dumas_64kb.mp3' }, 
         { id : 45, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_46_dumas_64kb.mp3' }, 
         { id : 46, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_47_dumas_64kb.mp3' }, 
         { id : 47, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_48_dumas_64kb.mp3' }, 
         { id : 48, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_49_dumas_64kb.mp3' }, 
         { id : 49, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_50_dumas_64kb.mp3' }, 
         { id : 50, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_51_dumas_64kb.mp3' }, 
         { id : 51, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_52_dumas_64kb.mp3' }, 
         { id : 52, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_53_dumas_64kb.mp3' }, 
         { id : 53, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_54_dumas_64kb.mp3' }, 
         { id : 54, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_55_dumas_64kb.mp3' }, 
         { id : 55, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_56_dumas_64kb.mp3' }, 
         { id : 56, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_57_dumas_64kb.mp3' }, 
         { id : 57, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_58_dumas_64kb.mp3' }, 
         { id : 58, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_59_dumas_64kb.mp3' }, 
         { id : 59, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_60_dumas_64kb.mp3' }, 
         { id : 60, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_61_dumas_64kb.mp3' }, 
         { id : 61, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_62_dumas_64kb.mp3' }, 
         { id : 62, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_63_dumas_64kb.mp3' }, 
         { id : 63, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_64_dumas_64kb.mp3' }, 
         { id : 64, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_65_dumas_64kb.mp3' }, 
         { id : 65, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_66_dumas_64kb.mp3' }, 
         { id : 66, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_67_dumas_64kb.mp3' }, 
         { id : 67, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_68_dumas_64kb.mp3' }, 
         { id : 68, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_69_dumas_64kb.mp3' }, 
         { id : 69, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_70_dumas_64kb.mp3' }, 
         { id : 70, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_71_dumas_64kb.mp3' }, 
         { id : 71, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_72_dumas_64kb.mp3' }, 
         { id : 72, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_73_dumas_64kb.mp3' }, 
         { id : 73, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_74_dumas_64kb.mp3' }, 
         { id : 74, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_75_dumas_64kb.mp3' }, 
         { id : 75, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_76_dumas_64kb.mp3' }, 
         { id : 76, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_77_dumas_64kb.mp3' }, 
         { id : 77, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_78_dumas_64kb.mp3' }, 
         { id : 78, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_79_dumas_64kb.mp3' }, 
         { id : 79, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_80_dumas_64kb.mp3' }, 
         { id : 80, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_81_dumas_64kb.mp3' }, 
         { id : 81, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_82_dumas_64kb.mp3' }, 
         { id : 82, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_83_dumas_64kb.mp3' }, 
         { id : 83, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_84_dumas_64kb.mp3' }, 
         { id : 84, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_85_dumas_64kb.mp3' }, 
         { id : 85, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_86_dumas_64kb.mp3' }, 
         { id : 86, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_87_dumas_64kb.mp3' }, 
         { id : 87, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_88_dumas_64kb.mp3' }, 
         { id : 88, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_89_dumas_64kb.mp3' }, 
         { id : 89, url :  ' http://www.archive.org/download/twentyyearsafter_0904_librivox/twentyyearsafter_90_dumas_64kb.mp3' }, 
        
                ]
        
                    
            },
        ]
    },
    {
        genre : 'Literary',
        id : 1,
        books : [
            { 
                id : 3,
                title : 'Letters of Two Brides',
                author : 'Balzac Honore De',
                description : 'The two brides are Louise de Chaulieu (Madame Gaston) and Renée de Maucombe (Madame lEstorade). The women became friends during their education at a convent and upon leaving began a life-long correspondence. For a 17 year period, they exchange letters describing their lives.Michelle Crandall reads Renee’s letters, and Kara Shallenberg reads Louise’s. Letters from the men in their lives are read by Peter Yearsley, David Barnes, Denny Sayers, and Sean McKinley.',
                img_url : 'https://prodimage.images-bn.com/pimages/9781727859676_p0_v1_s550x406.jpg',
                chapters : [
                    { id : 0, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_01_debalzac_64kb.mp3' }, 
                    { id : 1, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_02_debalzac_64kb.mp3' }, 
                    { id : 2, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_03_debalzac_64kb.mp3' }, 
                    { id : 3, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_04_debalzac_64kb.mp3' }, 
                    { id : 4, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_05_debalzac_64kb.mp3' }, 
                    { id : 5, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_06_debalzac_64kb.mp3' }, 
                    { id : 6, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_07_debalzac_64kb.mp3' }, 
                    { id : 7, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_08_debalzac_64kb.mp3' }, 
                    { id : 8, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_09_debalzac_64kb.mp3' }, 
                    { id : 9, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_10_debalzac_64kb.mp3' }, 
                    { id : 10, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_11_debalzac_64kb.mp3' }, 
                    { id : 11, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_12_debalzac_64kb.mp3' }, 
                    { id : 12, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_13_debalzac_64kb.mp3' }, 
                    { id : 13, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_14_debalzac_64kb.mp3' }, 
                    { id : 14, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_15_debalzac_64kb.mp3' }, 
                    { id : 15, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_16_debalzac_64kb.mp3' }, 
                    { id : 16, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_17_debalzac_64kb.mp3' }, 
                    { id : 17, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_18_debalzac_64kb.mp3' }, 
                    { id : 18, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_19_debalzac_64kb.mp3' }, 
                    { id : 19, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_20_debalzac_64kb.mp3' }, 
                    { id : 20, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_21_debalzac_64kb.mp3' }, 
                    { id : 21, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_22_debalzac_64kb.mp3' }, 
                    { id : 22, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_23_debalzac_64kb.mp3' }, 
                    { id : 23, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_24_debalzac_64kb.mp3' }, 
                    { id : 24, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_25_debalzac_64kb.mp3' }, 
                    { id : 25, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_26_debalzac_64kb.mp3' }, 
                    { id : 26, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_27_debalzac_64kb.mp3' }, 
                    { id : 27, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_28_debalzac_64kb.mp3' }, 
                    { id : 28, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_29_debalzac_64kb.mp3' }, 
                    { id : 29, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_30_debalzac_64kb.mp3' }, 
                    { id : 30, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_31_debalzac_64kb.mp3' }, 
                    { id : 31, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_32_debalzac_64kb.mp3' }, 
                    { id : 32, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_33_debalzac_64kb.mp3' }, 
                    { id : 33, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_34_debalzac_64kb.mp3' }, 
                    { id : 34, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_35_debalzac_64kb.mp3' }, 
                    { id : 35, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_36_debalzac_64kb.mp3' }, 
                    { id : 36, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_37_debalzac_64kb.mp3' }, 
                    { id : 37, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_38_debalzac_64kb.mp3' }, 
                    { id : 38, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_39_debalzac_64kb.mp3' }, 
                    { id : 39, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_40_debalzac_64kb.mp3' }, 
                    { id : 40, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_41_debalzac_64kb.mp3' }, 
                    { id : 41, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_42_debalzac_64kb.mp3' }, 
                    { id : 42, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_43_debalzac_64kb.mp3' }, 
                    { id : 43, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_44_debalzac_64kb.mp3' }, 
                    { id : 44, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_45_debalzac_64kb.mp3' }, 
                    { id : 45, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_46_debalzac_64kb.mp3' }, 
                    { id : 46, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_47_debalzac_64kb.mp3' }, 
                    { id : 47, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_48_debalzac_64kb.mp3' }, 
                    { id : 48, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_49_debalzac_64kb.mp3' }, 
                    { id : 49, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_50_debalzac_64kb.mp3' }, 
                    { id : 50, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_51_debalzac_64kb.mp3' }, 
                    { id : 51, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_52_debalzac_64kb.mp3' }, 
                    { id : 52, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_53_debalzac_64kb.mp3' }, 
                    { id : 53, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_54_debalzac_64kb.mp3' }, 
                    { id : 54, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_55_debalzac_64kb.mp3' }, 
                    { id : 55, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_56_debalzac_64kb.mp3' }, 
                    { id : 56, url :  ' http://www.archive.org/download/letters_brides_0709_librivox/letters_of_two_brides_57_debalzac_64kb.mp3' }, 
                ]
                    
            },
            { 
                id : 4,
                title : 'Bleak House ',
                author : 'Charles Dickens',
                description : 'Bleak House is the ninth novel by Charles Dickens, published in 20 monthly parts between March 1852 and September 1853. It is widely held to be one of Dickens finest and most complete novels, containing one of the most vast, complex and engaging arrays of minor characters and sub-plots in his entire canon. Dickens tells all of these both through the narrative of the novels heroine, Esther Summerson, and as an omniscient narrator. Memorable characters include the menacing lawyer Tulkinghorn, the friendly but depressive John Jarndyce and the childish Harold Skimpole. The plot concerns a long-running legal dispute (Jarndyce and Jarndyce) which has far-reaching consequences for all involved.',
                img_url : 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Bleakhouse_serial_cover.jpg/200px-Bleakhouse_serial_cover.jpg',
                chapters : [
                    { id : 0, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_01_dickens_64kb.mp3' }, 
                    { id : 1, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_02_dickens_64kb.mp3' }, 
                    { id : 2, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_03_dickens_64kb.mp3' }, 
                    { id : 3, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_04_dickens_64kb.mp3' }, 
                    { id : 4, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_05_dickens_64kb.mp3' }, 
                    { id : 5, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_06_dickens_64kb.mp3' }, 
                    { id : 6, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_07_dickens_64kb.mp3' }, 
                    { id : 7, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_08_dickens_64kb.mp3' }, 
                    { id : 8, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_09_dickens_64kb.mp3' }, 
                    { id : 9, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_10_dickens_64kb.mp3' }, 
                    { id : 10, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_11_dickens_64kb.mp3' }, 
                    { id : 11, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_12_dickens_64kb.mp3' }, 
                    { id : 12, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_13_dickens_64kb.mp3' }, 
                    { id : 13, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_14_dickens_64kb.mp3' }, 
                    { id : 14, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_15_dickens_64kb.mp3' }, 
                    { id : 15, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_16_dickens_64kb.mp3' }, 
                    { id : 16, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_17_dickens_64kb.mp3' }, 
                    { id : 17, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_18_dickens_64kb.mp3' }, 
                    { id : 18, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_19_dickens_64kb.mp3' }, 
                    { id : 19, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_20_dickens_64kb.mp3' }, 
                    { id : 20, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_21_dickens_64kb.mp3' }, 
                    { id : 21, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_22_dickens_64kb.mp3' }, 
                    { id : 22, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_23_dickens_64kb.mp3' }, 
                    { id : 23, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_24_dickens_64kb.mp3' }, 
                    { id : 24, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_25_dickens_64kb.mp3' }, 
                    { id : 25, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_26_dickens_64kb.mp3' }, 
                    { id : 26, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_27_dickens_64kb.mp3' }, 
                    { id : 27, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_28_dickens_64kb.mp3' }, 
                    { id : 28, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_29_dickens_64kb.mp3' }, 
                    { id : 29, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_30_dickens_64kb.mp3' }, 
                    { id : 30, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_31_dickens_64kb.mp3' }, 
                    { id : 31, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_32_dickens_64kb.mp3' }, 
                    { id : 32, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_33_dickens_64kb.mp3' }, 
                    { id : 33, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_34_dickens_64kb.mp3' }, 
                    { id : 34, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_35_dickens_64kb.mp3' }, 
                    { id : 35, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_36_dickens_64kb.mp3' }, 
                    { id : 36, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_37_dickens_64kb.mp3' }, 
                    { id : 37, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_38_dickens_64kb.mp3' }, 
                    { id : 38, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_39_dickens_64kb.mp3' }, 
                    { id : 39, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_40_dickens_64kb.mp3' }, 
                    { id : 40, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_41_dickens_64kb.mp3' }, 
                    { id : 41, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_42_dickens_64kb.mp3' }, 
                    { id : 42, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_43_dickens_64kb.mp3' }, 
                    { id : 43, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_44_dickens_64kb.mp3' }, 
                    { id : 44, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_45_dickens_64kb.mp3' }, 
                    { id : 45, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_46_dickens_64kb.mp3' }, 
                    { id : 46, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_47_dickens_64kb.mp3' }, 
                    { id : 47, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_48_dickens_64kb.mp3' }, 
                    { id : 48, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_49_dickens_64kb.mp3' }, 
                    { id : 49, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_50_dickens_64kb.mp3' }, 
                    { id : 50, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_51_dickens_64kb.mp3' }, 
                    { id : 51, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_52_dickens_64kb.mp3' }, 
                    { id : 52, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_53_dickens_64kb.mp3' }, 
                    { id : 53, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_54_dickens_64kb.mp3' }, 
                    { id : 54, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_55_dickens_64kb.mp3' }, 
                    { id : 55, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_56_dickens_64kb.mp3' }, 
                    { id : 56, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_57_dickens_64kb.mp3' }, 
                    { id : 57, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_58_dickens_64kb.mp3' }, 
                    { id : 58, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_59_dickens_64kb.mp3' }, 
                    { id : 59, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_60_dickens_64kb.mp3' }, 
                    { id : 60, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_61_dickens_64kb.mp3' }, 
                    { id : 61, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_62_dickens_64kb.mp3' }, 
                    { id : 62, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_63_dickens_64kb.mp3' }, 
                    { id : 63, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_64_dickens_64kb.mp3' }, 
                    { id : 64, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_65_dickens_64kb.mp3' }, 
                    { id : 65, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_66_dickens_64kb.mp3' }, 
                    { id : 66, url :  ' http://www.archive.org/download/bleak_house_cl_librivox/bleak_house_67_dickens_64kb.mp3' }, 
                   
                ]
            },
            { 
                id : 5,
                title : 'Secret Garden',
                author : 'Frances Burnett',
                description : 'Mary Lennox is a spoiled, middle-class, self-centred child who has been recently orphaned. She is accepted into the quiet and remote country house of an uncle, who has almost completely withdrawn into himself after the death of his wife. Mary gradually becomes drawn into the hidden side of the house: why does she hear the crying of a unseen child? Why is there an overgrown, walled garden, its door long locked',
                img_url : 'https://images-na.ssl-images-amazon.com/images/I/51pqVVCq-yL._SX335_BO1,204,203,200_.jpg',
                chapters : [
                    { id : 0, url :  ' http://www.archive.org/download/secret_garden_librivox/secretgarden_01_burnett_64kb.mp3' }, 
                    { id : 1, url :  ' http://www.archive.org/download/secret_garden_librivox/secretgarden_02_burnett_64kb.mp3' }, 
                    { id : 2, url :  ' http://www.archive.org/download/secret_garden_librivox/secretgarden_03_burnett_64kb.mp3' }, 
                    { id : 3, url :  ' http://www.archive.org/download/secret_garden_librivox/secretgarden_04_burnett_64kb.mp3' }, 
                    { id : 4, url :  ' http://www.archive.org/download/secret_garden_librivox/secretgarden_05_burnett_64kb.mp3' }, 
                    { id : 5, url :  ' http://www.archive.org/download/secret_garden_librivox/secretgarden_06_burnett_64kb.mp3' }, 
                    { id : 6, url :  ' http://www.archive.org/download/secret_garden_librivox/secretgarden_07_burnett_64kb.mp3' }, 
                    { id : 7, url :  ' http://www.archive.org/download/secret_garden_librivox/secretgarden_08_burnett_64kb.mp3' }, 
                    { id : 8, url :  ' http://www.archive.org/download/secret_garden_librivox/secretgarden_09_burnett_64kb.mp3' }, 
                    { id : 9, url :  ' http://www.archive.org/download/secret_garden_librivox/secretgarden_10_burnett_64kb.mp3' }, 
                    { id : 10, url :  ' http://www.archive.org/download/secret_garden_librivox/secretgarden_11_burnett_64kb.mp3' }, 
                    { id : 11, url :  ' http://www.archive.org/download/secret_garden_librivox/secretgarden_12_burnett_64kb.mp3' }, 
                    { id : 12, url :  ' http://www.archive.org/download/secret_garden_librivox/secretgarden_13_burnett_64kb.mp3' }, 
                    { id : 13, url :  ' http://www.archive.org/download/secret_garden_librivox/secretgarden_14_burnett_64kb.mp3' }, 
                    { id : 14, url :  ' http://www.archive.org/download/secret_garden_librivox/secretgarden_15_burnett_64kb.mp3' }, 
                    { id : 15, url :  ' http://www.archive.org/download/secret_garden_librivox/secretgarden_16_burnett_64kb.mp3' }, 
                    { id : 16, url :  ' http://www.archive.org/download/secret_garden_librivox/secretgarden_17_burnett_64kb.mp3' }, 
                    { id : 17, url :  ' http://www.archive.org/download/secret_garden_librivox/secretgarden_18_burnett_64kb.mp3' }, 
                    { id : 18, url :  ' http://www.archive.org/download/secret_garden_librivox/secretgarden_19_burnett_64kb.mp3' }, 
                    { id : 19, url :  ' http://www.archive.org/download/secret_garden_librivox/secretgarden_20_burnett_64kb.mp3' }, 
                    { id : 20, url :  ' http://www.archive.org/download/secret_garden_librivox/secretgarden_21_burnett_64kb.mp3' }, 
                    { id : 21, url :  ' http://www.archive.org/download/secret_garden_librivox/secretgarden_22_burnett_64kb.mp3' }, 
                    { id : 22, url :  ' http://www.archive.org/download/secret_garden_librivox/secretgarden_23_burnett_64kb.mp3' }, 
                    { id : 23, url :  ' http://www.archive.org/download/secret_garden_librivox/secretgarden_24_burnett_64kb.mp3' }, 
                    { id : 24, url :  ' http://www.archive.org/download/secret_garden_librivox/secretgarden_25_burnett_64kb.mp3' }, 
                    { id : 25, url :  ' http://www.archive.org/download/secret_garden_librivox/secretgarden_26_burnett_64kb.mp3' }, 
                    { id : 26, url :  ' http://www.archive.org/download/secret_garden_librivox/secretgarden_27_burnett_64kb.mp3' }, 
                ]
            },
            {
                id : 6, //last
                title : 'Heart of Darkness',
                author : 'Joseph Conrad',
                description : 'Set in a time of oppressive colonisation, when large areas of the world were still unknown to Europe, and Africa was literally on maps and minds as a mysterious shadow, Heart of Darkness famously explores the rituals of civilisation and barbarism, and the frighteningly fine line between them.We get the tale through a classic unreliable narrator, relating as Marlow, a ship’s captain, tells how he was sent by the Company to retrieve the wayward Kurtz, and was shaken to discover the true depths of darkness in that creature’s, and in his own, soul. Conrad based the work closely on his own terrible experience in the Congo. This work has been reinterpreted and adapted into many modern forms, the most well known being the film Apocalypse Now.',
                img_url : 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1391926381l/8322133.jpg',
                chapters : [
                    { id : 0, url :  ' http://www.archive.org/download/heart_of_darkness/heart_of_darkness_1a_conrad_64kb.mp3' }, 
                    { id : 1, url :  ' http://www.archive.org/download/heart_of_darkness/heart_of_darkness_1b_conrad_64kb.mp3' }, 
                    { id : 2, url :  ' http://www.archive.org/download/heart_of_darkness/heart_of_darkness_2a_conrad_64kb.mp3' }, 
                    { id : 3, url :  ' http://www.archive.org/download/heart_of_darkness/heart_of_darkness_2b_conrad_64kb.mp3' }, 
                    { id : 4, url :  ' http://www.archive.org/download/heart_of_darkness/heart_of_darkness_3a_conrad_64kb.mp3' }, 
                    { id : 5, url :  ' http://www.archive.org/download/heart_of_darkness/heart_of_darkness_3b_conrad_64kb.mp3' }, 
                   
                ]
            },
            
        ]
    },
    {
        genre : 'History',
        id : 2,
        books : [
            {
                id : 7,
                title : 'Penguin Island',
                author : 'Anatole France',
                description : 'The novel (original French title -- LÎle des Pingouins) is a satire on human nature. The first publication was in 1908. These penguins are mistaken for humans by the 97-year-old priest, Father Mael, because of his bad eyesight. He baptizes them, and once baptized, they have no choice but to become human. They take on human traits (build civilizations, go to war, etc.). The book is very funny and powerful.',
                img_url : 'https://pictures.abebooks.com/isbn/9781434479280-us.jpg',
                chapters : [
                    { id : 0, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_01_france_64kb.mp3' }, 
                    { id : 1, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_02_france_64kb.mp3' }, 
                    { id : 2, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_03_france_64kb.mp3' }, 
                    { id : 3, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_04_france_64kb.mp3' }, 
                    { id : 4, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_05_france_64kb.mp3' }, 
                    { id : 5, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_06_france_64kb.mp3' }, 
                    { id : 6, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_07_france_64kb.mp3' }, 
                    { id : 7, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_08_france_64kb.mp3' }, 
                    { id : 8, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_09_france_64kb.mp3' }, 
                    { id : 9, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_10_france_64kb.mp3' }, 
                    { id : 10, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_11_france_64kb.mp3' }, 
                    { id : 11, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_12_france_64kb.mp3' }, 
                    { id : 12, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_13_france_64kb.mp3' }, 
                    { id : 13, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_14_france_64kb.mp3' }, 
                    { id : 14, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_15_france_64kb.mp3' }, 
                    { id : 15, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_16_france_64kb.mp3' }, 
                    { id : 16, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_17_france_64kb.mp3' }, 
                    { id : 17, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_18_france_64kb.mp3' }, 
                    { id : 18, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_19_france_64kb.mp3' }, 
                    { id : 19, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_20_france_64kb.mp3' }, 
                    { id : 20, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_21_france_64kb.mp3' }, 
                    { id : 21, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_22_france_64kb.mp3' }, 
                    { id : 22, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_23_france_64kb.mp3' }, 
                    { id : 23, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_24_france_64kb.mp3' }, 
                    { id : 24, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_25_france_64kb.mp3' }, 
                    { id : 25, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_26_france_64kb.mp3' }, 
                    { id : 26, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_27_france_64kb.mp3' }, 
                    { id : 27, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_28_france_64kb.mp3' }, 
                    { id : 28, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_29_france_64kb.mp3' }, 
                    { id : 29, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_30_france_64kb.mp3' }, 
                    { id : 30, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_31_france_64kb.mp3' }, 
                    { id : 31, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_32_france_64kb.mp3' }, 
                    { id : 32, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_33_france_64kb.mp3' }, 
                    { id : 33, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_34_france_64kb.mp3' }, 
                    { id : 34, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_35_france_64kb.mp3' }, 
                    { id : 35, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_36_france_64kb.mp3' }, 
                    { id : 36, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_37_france_64kb.mp3' }, 
                    { id : 37, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_38_france_64kb.mp3' }, 
                    { id : 38, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_39_france_64kb.mp3' }, 
                    { id : 39, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_40_france_64kb.mp3' }, 
                    { id : 40, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_41_france_64kb.mp3' }, 
                    { id : 41, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_42_france_64kb.mp3' }, 
                    { id : 42, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_43_france_64kb.mp3' }, 
                    { id : 43, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_44_france_64kb.mp3' }, 
                    { id : 44, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_45_france_64kb.mp3' }, 
                    { id : 45, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_46_france_64kb.mp3' }, 
                    { id : 46, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_47_france_64kb.mp3' }, 
                    { id : 47, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_48_france_64kb.mp3' }, 
                    { id : 48, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_49_france_64kb.mp3' }, 
                    { id : 49, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_50_france_64kb.mp3' }, 
                    { id : 50, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_51_france_64kb.mp3' }, 
                    { id : 51, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_52_france_64kb.mp3' }, 
                    { id : 52, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_53_france_64kb.mp3' }, 
                    { id : 53, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_54_france_64kb.mp3' }, 
                    { id : 54, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_55_france_64kb.mp3' }, 
                    { id : 55, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_56_france_64kb.mp3' }, 
                    { id : 56, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_57_france_64kb.mp3' }, 
                    { id : 57, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_58_france_64kb.mp3' }, 
                    { id : 58, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_59_france_64kb.mp3' }, 
                    { id : 59, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_60_france_64kb.mp3' }, 
                    { id : 60, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_61_france_64kb.mp3' }, 
                    { id : 61, url :  ' http://www.archive.org/download/penguin_island_ms_librivox/penguin_island_62_france_64kb.mp3' }, 
                   
                ]
            },
            
            
        ]
    },
    {
        genre : 'Adventure',
        id : 3,
        books : [
            { 
                id : 8,
                title : 'Adventures of Huckleberry Finn',
                author : 'Mark Twain',
                description : 'Adventures of Huckleberry Finn (1884) by Mark Twain is one of the truly great American novels, beloved by children, adults, and literary critics alike.  The book tells the story of “Huck” Finn (first introduced as Tom Sawyer’s sidekick in The Adventures of Tom Sawyer), his friend Jim, and their journey down the Mississippi River on a raft.  Both are on the run, Huck from his drunk and abusive father, and Jim as a runaway slave.As Huck and Jim drift down the river, they meet many colorful characters and have many great adventures.  The true heart of the story, however, is the friendship between Huck and Jim.  A constant theme throughout the book is Hucks internal struggle between what he has been taught, that helping a runaway slave is a sin, and what he truly believes, that Jim is a good man and it couldn’t possibly be wrong to help him.Adventures of Huckleberry Finn was unique at the time of its publication (1884) because it is narrated by Huck himself and is written in the numerous dialects common in the area and time in which the book is set.  Although the book was originally intended as a sequel to the childrens book The Adventures of Tom Sawyer, as Twain wrote Adventures of Huckleberry Finn it progressed into a more serious work.  Twains views on slavery and other social issues of the time become clear through the words, thoughts, and actions of Huck Finn.  The book has always been the subject of great controversy, and according to The American Library Association it was fifth on the list of most frequently challenged books in the 1990s.',
                img_url : 'https://www.rif.org/sites/default/files/Book_Covers/huckleberry.jpg',
                chapters : [
                    { id : 0, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_01_twain_apc_64kb.mp3' }, 
         { id : 1, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_02_twain_apc_64kb.mp3' }, 
         { id : 2, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_03_twain_apc_64kb.mp3' }, 
         { id : 3, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_04_twain_apc_64kb.mp3' }, 
         { id : 4, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_05_twain_apc_64kb.mp3' }, 
         { id : 5, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_06_twain_apc_64kb.mp3' }, 
         { id : 6, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_07_twain_apc_64kb.mp3' }, 
         { id : 7, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_08_twain_apc_64kb.mp3' }, 
         { id : 8, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_09_twain_apc_64kb.mp3' }, 
         { id : 9, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_10_twain_apc_64kb.mp3' }, 
         { id : 10, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_11_twain_apc_64kb.mp3' }, 
         { id : 11, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_12_twain_apc_64kb.mp3' }, 
         { id : 12, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_13_twain_apc_64kb.mp3' }, 
         { id : 13, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_14_twain_apc_64kb.mp3' }, 
         { id : 14, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_15_twain_apc_64kb.mp3' }, 
         { id : 15, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_16_twain_apc_64kb.mp3' }, 
         { id : 16, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_17_twain_apc_64kb.mp3' }, 
         { id : 17, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_18_twain_apc_64kb.mp3' }, 
         { id : 18, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_19_twain_apc_64kb.mp3' }, 
         { id : 19, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_20_twain_apc_64kb.mp3' }, 
         { id : 20, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_21_twain_apc_64kb.mp3' }, 
         { id : 21, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_22_twain_apc_64kb.mp3' }, 
         { id : 22, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_23_twain_apc_64kb.mp3' }, 
         { id : 23, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_24_twain_apc_64kb.mp3' }, 
         { id : 24, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_25_twain_apc_64kb.mp3' }, 
         { id : 25, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_26_twain_apc_64kb.mp3' }, 
         { id : 26, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_27_twain_apc_64kb.mp3' }, 
         { id : 27, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_28_twain_apc_64kb.mp3' }, 
         { id : 28, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_29_twain_apc_64kb.mp3' }, 
         { id : 29, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_30_twain_apc_64kb.mp3' }, 
         { id : 30, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_31_twain_apc_64kb.mp3' }, 
         { id : 31, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_32_twain_apc_64kb.mp3' }, 
         { id : 32, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_33_twain_apc_64kb.mp3' }, 
         { id : 33, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_34_twain_apc_64kb.mp3' }, 
         { id : 34, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_35_twain_apc_64kb.mp3' }, 
         { id : 35, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_36_twain_apc_64kb.mp3' }, 
         { id : 36, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_37_twain_apc_64kb.mp3' }, 
         { id : 37, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_38_twain_apc_64kb.mp3' }, 
         { id : 38, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_39_twain_apc_64kb.mp3' }, 
         { id : 39, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_40_twain_apc_64kb.mp3' }, 
         { id : 40, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_41_twain_apc_64kb.mp3' }, 
         { id : 41, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_42_twain_apc_64kb.mp3' }, 
         { id : 42, url :  ' http://www.archive.org/download/huck_finn_librivox/huckfinn_43_twain_apc_64kb.mp3' }, 
        
                ]
        
                    
            },
            
        ]
    },

]

export default AUDIO_DATA;